

const data = [
        {
            name: 'Terrace House',
            img: '/images/terraces.jpg',
            location: 'Lekki',
            landSize: '1250sqm',
            price: 211,
            contact: 'Agent Simple',
            document: 'Terrace',
            id: 1,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/terrace-1.jpg',
            location: 'Lagos-mainland',
            landSize: '850sqm',
            price: 133,
            contact: 'Agent Simple',
            document: 'Terrace',
            id:2,
            title: '2 Bedroom Terrace House with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/bungalow.jpg',
            location: 'Abuja',
            landSize: '750sqm',
            price: 209,
            contact: 'Agent Giyu',
            document: 'Terrace',
            id:3,
            title: '3 Bedroom Terrace House',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow.jpg',
            location: 'lagos-Ikeja',
            landSize: '750sqm',
            price: 120,
            contact: 'Surveyor Samad',
            document: 'Bungalow',
            id:4,
            title: '2 Bedroom Terrace Duplex with BQ',
            phone: '08122651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-2.jpg',
            location: 'Ikeja',
            landSize: '850sqm',
            price: 97,
            contact: 'Surveyor Samad',
            document: 'Bungalow',
            id:5,
            title: '3 Bedroom Flat ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-3.jpg',
            location: 'Lagos-mainland',
            landSize: '850sqm',
            price: 187,
            contact: 'Agent Simple',
            document: 'Bungalow',
            id:5,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-sale.jpg',
            location: 'Ikeja',
            landSize: '850sqm',
            price: 119,
            contact: 'Agent Simple',
            document: 'Bungalow',
            id:6,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Commercial',
            img: '/images/bungalow.jpg',
            location: 'Ketu Ojota',
            landSize: '850sqm',
            price: 200,
            contact: 'Agent Giyu',
            document: 'Commercial',
            id:7,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Residential',
            img: '/images/residential.jpg',
            location: 'Anthony Oshodi',
            landSize: '850sqm',
            price: 80,
            contact: 'Agent Simple',
            document: 'Residential',
            id:8,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Serviced Apartment',
            img: '/images/residential.jpg',
            location: 'Ikorodu',
            landSize: '850sqm',
            price: 320,
            contact: 'Surveyor Samad',
            document: 'Serviced',
            id:9,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Get your House Duplexes',
            img: '/images/get-key.jpg',
            location: 'Songotedo Ajah',
            landSize: '850sqm',
            price: 120,
            contact: 'Agent Simple',
            document: 'Duplexes',
            id:10,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Real Estate Detached',
            img: '/images/serviced-1.jpg',
            location: 'Ibeju-Lekki',
            landSize: '850sqm',
            price: 170,
            contact: 'Agent Giyu',
            document: 'Detached',
            id:11,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Service Apartment',
            img: '/images/serviced-2.jpg',
            location: 'Ikoyi',
            landSize: '850sqm',
            price: 160,
            contact: 'Surveyor Mubaraq',
            document: 'Serviced',
            id:12,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/bungalow-2.jpg',
            location: 'Lekki',
            landSize: '850sqm',
            price: 120,
            contact: 'Surveyor Mubaraq',
            document: 'Terraces',
            id:13,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/real-estate.jpg',
            location: 'Lekki',
            landSize: '850sqm',
            price: 220,
            contact: 'Surveyor Samad',
            document: 'Terrace',
            id:14,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/real-estate.jpg',
            location: 'Lekki',
            landSize: '850sqm',
            price: 40,
            contact: 'Agent Simple',
            document: 'Terrace',
            id:15,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/terraces.jpg',
            location: 'Lekki',
            landSize: '1250sqm',
            price: 211,
            contact: 'Agent Nutjob',
            document: 'Terrace',
            id:16,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]

        },
        {
            name: 'Terrace House',
            img: '/images/terrace-1.jpg',
            location: 'Mushin',
            landSize: '850sqm',
            price: 133,
            contact: 'Agent Nutjob',
            document: 'Terrace',
            id:17,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/bungalow.jpg',
            location: 'Abuja',
            landSize: '750sqm',
            price: 209,
            contact: 'Surveyor Natacha',
            document: 'Terrace',
            id:18,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow.jpg',
            location: 'lagos-Ikeja',
            landSize: '750sqm',
            price: 120,
            contact: 'Agent Clinton',
            document: 'Bungalow',
            id:19,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-2.jpg',
            location: 'Ikeja',
            landSize: '850sqm',
            price: 97,
            contact: 'Agent Simple',
            document: 'Bungalow',
            id:20,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-3.jpg',
            location: 'Festac',
            landSize: '850sqm',
            price: 187,
            contact: 'Surveyor Viktor',
            document: 'Bungalow',
            id:21,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Bungalow',
            img: '/images/bungalow-sale.jpg',
            location: 'Lagos-mainland',
            landSize: '850sqm',
            price: 119,
            contact: 'Agent Wayne',
            document: 'Bungalow',
            id:22,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Commercial',
            img: '/images/bungalow.jpg',
            location: 'Igando-Ikotun',
            landSize: '850sqm',
            price: 200,
            contact: 'Surveyor Mubaraq',
            document: 'Commercial',
            id:23,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Residential',
            img: '/images/residential.jpg',
            location: 'Surulere',
            landSize: '850sqm',
            price: 80,
            contact: 'Agent Simple',
            document: 'Residential',
            id:24,
            title: '12 nos. 2 Bedroom Flat',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Serviced Apartment',
            img: '/images/residential.jpg',
            location: 'Ibeju-lekki',
            landSize: '850sqm',
            price: 320,
            contact: 'Agent Giyu',
            document: 'Serviced',
            id:25,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Get your House Duplexes',
            img: '/images/get-key.jpg',
            location: 'Ikoyi',
            landSize: '850sqm',
            price: 120,
            contact: 'Surveyor Natacha',
            document: 'Duplexes',
            id:26,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Real Estate Detached',
            img: '/images/serviced-1.jpg',
            location: 'Gbagada',
            landSize: '850sqm',
            price: 170,
            contact: 'Agent Simple',
            document: 'Detached',
            id:27,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Service Apartment',
            img: '/images/serviced-2.jpg',
            location: 'Oshodi-Isolo',
            landSize: '850sqm',
            price: 160,
            contact: 'Surveyor Natacha',
            document: 'Serviced',
            id:28,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/bungalow-2.jpg',
            location: 'Lagos-mainland',
            landSize: '850sqm',
            price: 120,
            contact: 'Agent Nutjob',
            document: 'Terraces',
            id:29,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/real-estate.jpg',
            location: 'Iyana-Ipaja',
            landSize: '850sqm',
            price: 220,
            contact: 'Agent Nutjob',
            document: 'Terrace',
            id:30,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
        {
            name: 'Terrace House',
            img: '/images/real-estate.jpg',
            location: 'Shomolu Mile 2',
            landSize: '850sqm',
            price: 40,
            contact: 'Surveyor Natacha',
            document: 'Terrace',
            id:31,
            title: '4 Bedroom Terrace Duplex with BQ',
            phone: '08145651777',
            interior: [
                '/images/interior1.jpg',
                '/images/interior2.jpg',
                '/images/interior3.jpg',
                '/images/interior6.jpg',
                '/images/interior4.jpg',
                '/images/interior5.jpg',
                '/images/interior6.jpg',
            ]
        },
    ]

export default data